steps:

  # Build app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/my-repo/hello:$COMMIT_SHA', '.']
    id: BUILD

  # Storage of the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/my-repo/hello:$COMMIT_SHA']
    id: STORAGE

  # Deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'hello-site',
          '--image', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/my-repo/hello:$COMMIT_SHA',
          '--region', 'southamerica-east1',
          '--platform', 'managed',
          '--allow-unauthenticated']
    id: DEPLOY

